import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../repositories/providers.dart';

class WelcomeScreen extends StatelessWidget { const WelcomeScreen({super.key}); @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.all(24), child:Column(mainAxisAlignment:MainAxisAlignment.center, crossAxisAlignment:CrossAxisAlignment.stretch, children:[Icon(Icons.spa_outlined,size:80,color:Theme.of(context).colorScheme.primary), Text('Welcome to Zaylo',textAlign:TextAlign.center,style:Theme.of(context).textTheme.headlineMedium), const SizedBox(height:8), const Text('Everyday tools for your money, community, opportunities and learning.',textAlign:TextAlign.center), const SizedBox(height:28), ElevatedButton(onPressed:()=>context.go('/signin'), child:const Text('Sign in')), OutlinedButton(onPressed:()=>context.go('/create-account'), child:const Text('Create account'))])))); }
class SignInScreen extends ConsumerStatefulWidget { const SignInScreen({super.key}); @override ConsumerState<SignInScreen> createState()=>_SignInScreenState(); }
class _SignInScreenState extends ConsumerState<SignInScreen>{ final key=GlobalKey<FormState>(); @override Widget build(BuildContext context)=>AuthFormScaffold(title:'Sign in', children:[Form(key:key, child:Column(children:[TextFormField(key:const Key('emailField'), decoration:const InputDecoration(labelText:'Email'), validator:(v)=>v!=null&&v.contains('@')?null:'Enter a valid email'), const SizedBox(height:12), TextFormField(key:const Key('passwordField'), decoration:const InputDecoration(labelText:'Password'), obscureText:true, validator:(v)=>(v??'').length>=6?null:'Password must be at least 6 characters'), Align(alignment:Alignment.centerRight, child:TextButton(onPressed:()=>context.go('/forgot-password'), child:const Text('Forgot password?'))), ElevatedButton(key:const Key('signInButton'), onPressed:(){if(key.currentState!.validate()){ref.read(authProvider.notifier).signIn(); context.go('/home');}}, child:const Text('Sign in'))]))]); }
class CreateAccountScreen extends ConsumerStatefulWidget{ const CreateAccountScreen({super.key}); @override ConsumerState<CreateAccountScreen> createState()=>_CreateAccountScreenState(); }
class _CreateAccountScreenState extends ConsumerState<CreateAccountScreen>{ final key=GlobalKey<FormState>(); @override Widget build(BuildContext context)=>AuthFormScaffold(title:'Create account', children:[Form(key:key, child:Column(children:[for(final label in ['Full name','Email','Password','Country','City']) Padding(padding:const EdgeInsets.only(bottom:12), child:TextFormField(decoration:InputDecoration(labelText:label), obscureText:label=='Password', validator:(v)=>(v??'').isEmpty?'Required':null)), ElevatedButton(onPressed:(){if(key.currentState!.validate()){ref.read(authProvider.notifier).signIn(); context.go('/home');}}, child:const Text('Create account'))]))]); }
class ForgotPasswordScreen extends StatelessWidget{ const ForgotPasswordScreen({super.key}); @override Widget build(BuildContext context)=>AuthFormScaffold(title:'Forgot password', children:[TextFormField(decoration:const InputDecoration(labelText:'Email')), const SizedBox(height:12), ElevatedButton(onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Password reset email mocked for MVP.'))), child:const Text('Send reset link'))]); }
class AuthFormScaffold extends StatelessWidget{ const AuthFormScaffold({super.key,required this.title,required this.children}); final String title; final List<Widget> children; @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(), body:ListView(padding:const EdgeInsets.all(24), children:[Text(title,style:Theme.of(context).textTheme.headlineMedium), const SizedBox(height:20), ...children])); }
